# Generated by Django 3.2 on 2021-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confroom',
            name='projector_availability',
            field=models.BooleanField(default=False),
        ),
    ]
