# Generated by Django 3.2 on 2021-04-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0002_alter_confroom_projector_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confroom',
            name='projector_availability',
        ),
    ]
