# Generated by Django 3.2 on 2021-04-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceRoom', '0003_remove_confroom_projector_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='confroom',
            name='projector_availability',
            field=models.BooleanField(default=False),
        ),
    ]
